### ISSUE TITLE
Think about licencing

### ISSUE THREAD

**Issue by heavy-lifting** [patternclub/patternclub.github.io#1]
Since we are intending to share resources and for other people to copy what we're doing then it probably makes sense to be clear about our licence (also helpful if we are asking others to share materials/resources with us to publish on the site)

I'm not an expert but maybe [CC-BY-SA-4.0](https://choosealicense.com/licenses/cc-by-sa-4.0/) might be a good choice?

**Comment by yaxu** [comment]
Yep I like cc-by-sa !

**Comment by heavy-lifting** [comment]
COOL! I've added the text into the repo :)
